"""Contract gate: check that mocked requests hit routes Zou actually serves.

The gazu test suite mocks the exact URL each wrapper builds, so a wrong path
in gazu and the same wrong path in the test cancel out. This gate matches
every API request against a snapshot of Zou's real route table
(``tests/fixtures/zou_routes.json``, regenerated by
``scripts/extract_zou_routes.py``) so an invented endpoint fails the test.

Limitation: the generic CRUD routes are ``/data/<model>/<id>``, and test IDs
are not UUIDs (e.g. "shot-01"), so a bad path shaped like ``/data/tasks/open``
can't be told apart from a real get-by-id and slips through. The gate still
catches the bulk of invented routes (extra path segments, wrong prefixes like
``pictures/`` vs ``actions/``, made-up sub-resources).
"""

import json
import os
import re
from urllib.parse import urlparse

_HERE = os.path.dirname(__file__)

with open(os.path.join(_HERE, "fixtures", "zou_routes.json")) as _f:
    _ROUTES = json.load(_f)


def _to_regex(route):
    # "/data/tasks/<task_id>" -> ^/data/tasks/[^/]+$
    parts = re.split(r"<[^>]+>", route)
    return re.compile("^" + "[^/]+".join(re.escape(p) for p in parts) + "$")


_PATTERNS = [_to_regex(r) for r in _ROUTES]

# Endpoints that are legitimate but not in the blueprint route snapshot
# (test helpers, non-CRUD utility endpoints, and the API root).
_ALLOWED_EXACT = {
    "/",
    "/auth/login",
    "/auth/logout",
    "/auth/authenticated",
    "/auth/refresh-token",
    "/auth/email-otp",
    "/test",
    "/test_url",
    # Dummy path the upload primitive tests post to (not a gazu wrapper).
    "/data/new-file",
}

# Known-broken routes still shipped by gazu, pending a fix or a decision.
# This list must only shrink. See .audit/checklist-2026-07-03.md (BUG-2/3).
_ALLOWED_BROKEN = {
    # user.py all_*_for_* (user_context): no user-scoped route in Zou.
    # Removing them changes context.py behavior -> needs a decision.
    "/data/user/projects/<project_id>/assets",
    "/data/user/projects/<project_id>/scenes",
    "/data/user/episodes/<project_id>/sequences",
    # get_project_quotas / get_project_person_quotas: Zou serves
    # quotas/<task_type_id> and quotas/persons/<person_id>, not these bare
    # paths. Surfaced by this gate; needs the intended API confirmed.
    "/data/projects/<project_id>/quotas",
    "/data/projects/<project_id>/person-quotas",
}
_BROKEN_PATTERNS = [_to_regex(r) for r in _ALLOWED_BROKEN]


def request_path(url):
    """Return the Zou-relative path of a request URL, or None if external."""
    path = urlparse(url).path
    if path.startswith("/api"):
        path = path[len("/api") :] or "/"
    else:
        # Not a gazu API call (e.g. an arbitrary download URL): skip it.
        return None
    return path.rstrip("/") or "/"


def is_known_route(path):
    if path in _ALLOWED_EXACT:
        return True
    if any(p.match(path) for p in _PATTERNS):
        return True
    if any(p.match(path) for p in _BROKEN_PATTERNS):
        return True
    return False
